# Generated by Django 3.2.16 on 2022-10-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('birth_date', models.DateField(blank=True, verbose_name='Date of birth')),
                ('aim', models.CharField(max_length=100, verbose_name='Training objective')),
            ],
        ),
    ]
