# Generated by Django 3.2.16 on 2022-10-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Status of homework'),
        ),
    ]
