# Generated by Django 3.2.16 on 2023-02-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20230123_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Addition date'),
        ),
    ]
