# Generated by Django 3.2.16 on 2022-10-22 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0004_alter_homework_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
