# Generated by Django 3.2.19 on 2023-05-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_dictionary_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='transcription',
            field=models.CharField(default='-', max_length=150),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='translation',
            field=models.CharField(max_length=200),
        ),
    ]
