# # Generated by Django 3.2.19 on 2023-06-11 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20230524_1155'),
        ('dictionary', '0002_copy_old_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dictionary',
        ),
    ]
