version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./.env

  rabbitmq:
    image: rabbitmq:3.11-management
    hostname: rabbitmq
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 20s
      timeout: 10s
      retries: 5

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

  base: &app_base
    # image: rezenhorn/english:latest
    build: ../english
    env_file:
      - ./.env

  web:
    <<: *app_base
    restart: always
    command: gunicorn english.wsgi:application --bind 0:8000
    ports:
      - 8000:8000
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
      - rabbitmq
      - redis
      - migrations
      - collectstatic

  migrations:
    <<: *app_base
    restart: on-failure
    command: python manage.py migrate
    depends_on:
      - db

  collectstatic:
    <<: *app_base
    command: python manage.py collectstatic --noinput

  celery:
    <<: *app_base
    command: celery -A english worker --uid=nobody --gid=nogroup --loglevel=info
    restart: on-failure
    volumes:
      - .:/usr/src/app
    depends_on:
      web:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

volumes:
  static_value:
  media_value:
  database:
  rabbitmq:
