# Generated by Django 3.2.19 on 2023-06-11 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('translation', models.CharField(max_length=200)),
                ('transcription', models.CharField(default='-', max_length=150)),
                ('example', models.CharField(blank=True, help_text='A sentence with the word', max_length=150, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='Addition date')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name_plural': 'Dictionaries',
                'ordering': ('word',),
            },
        ),
    ]
