# Generated by Django 3.2.20 on 2023-07-31 14:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0002_copy_old_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dictionary',
            new_name='Word',
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ('word',)},
        ),
    ]
